language: cpp
compiler: clang
os: osx
osx_image: xcode11.3
before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -S . -B build -DCMAKE_CXX_FLAGS="-ftest-coverage -fprofile-arcs"
  - make -C build
  - ./n_puzzle_tests
after_success:
  ~/Library/Python/2.7/bin/cpp-coveralls --root . -i include/Exceptions.hpp -i include/Heuristics -i include/Move.hpp -i include/Node.hpp -i include/Output.hpp -i include/Parser.hpp -i include/Puzzle.hpp -i include/Solver.hpp -i src/n_puzzle_lib
